# Generated by Django 4.2 on 2024-04-18 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_project_pub_date_alter_projectentry_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_start'], 'permissions': [('can_manage_projects', 'Can manage projects'), ('can_moderate_projects', 'Can moderate incoming projects'), ('can_create_projects', 'Can create projects'), ('can_enter_projects', 'Can enter projects'), ('can_view_project_details', 'Can view project details')]},
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 11, 9, 54, 232223, tzinfo=datetime.timezone.utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 11, 9, 54, 234223, tzinfo=datetime.timezone.utc), verbose_name='Время, когда заяка была отправлена'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 11, 9, 54, 234223, tzinfo=datetime.timezone.utc), verbose_name='Время, когда статус заявки был изменен'),
        ),
        migrations.AlterField(
            model_name='projectnotice',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 11, 9, 54, 235222, tzinfo=datetime.timezone.utc)),
        ),
    ]
