# Generated by Django 4.2 on 2024-05-14 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_custom_add_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='direction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.direction'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 4, 58, 35, 645184, tzinfo=datetime.timezone.utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 4, 58, 35, 646690, tzinfo=datetime.timezone.utc), verbose_name='Время, когда заяка была отправлена'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 4, 58, 35, 646690, tzinfo=datetime.timezone.utc), verbose_name='Время, когда статус заявки был изменен'),
        ),
        migrations.AlterField(
            model_name='projectnotice',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 4, 58, 35, 647695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
