# Generated by Django 4.2 on 2024-05-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0003_alter_profile_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_info',
            field=models.CharField(help_text='Введите номер телефона', max_length=18, verbose_name='Contact Information'),
        ),
    ]
