# Generated by Django 4.2 on 2024-04-07 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0013_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 20, 8, 27, 827709, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
