# Generated by Django 4.2 on 2024-05-14 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0018_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 5, 14, 33, 732107, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
