# Generated by Django 4.2 on 2024-05-27 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0022_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 18, 7, 27, 110756, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
