# Generated by Django 4.2 on 2024-06-25 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0024_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 12, 44, 48, 246151, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
