# Generated by Django 4.2 on 2024-07-02 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0029_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 2, 8, 15, 15, 191522, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
